server:
    port: 8761

spring:
    application:
        name: jasonlocalhost-eureka

# 单机模式
eureka:
    client:
        registerWithEureka: false # 服务注册, 是否将自己注册到Eureka服务中，本身就是所有无需注册
        fetchRegistry: false # 服务发现, 是否从Eureka中获取注册信息
        serviceUrl: # Eureka客户端与Eureka服务端进行交互的地址
            defaultZone: http://localhost:${server.port}/eureka/
    server:
        enable-self-preservation: false # 是否开启自我保护模式
        eviction-interval-timer-in-ms: 60000 # 服务注册表清理间隔（单位毫秒，默认是60*1000)

# 高可用模式
# eureka:
#     client:
#         register-with-eureka: true # 是否需要往Eureka注册
#         fetch-registry: true # 是否需要从Eureka获取注册信息
#         service-url:  # Eureka注册地址
#             defaultZone: http://localhost:8762/eureka
