spring:
    application:
        name: jasonlocalhost-management-service

app:
    id: jlh-service

apollo:
    cluster: management # 指定集群
    property:
        order:
            enable: true # 开启按顺序加载配置, 适用于对加载配置的顺序有要求时, 如spring cloud zuul的路由规则
    bootstrap:
        eagerLoad:
            enabled: true # 开启主动加载
        enabled: true # 开启启动阶段加载配置
        namespaces: dev_dept.application, dev_dept.datasource # 指定需要加载的命名空间的配置
