spring:
    application:
        name: jasonlocalhost-management-service

app:
    id: jlh-management # 指定appid

apollo:
    property:
        order:
            enable: true # 开启按顺序加载配置, 适用于对加载配置的顺序有要求时, 如spring cloud zuul的路由规则
    bootstrap:
        eagerLoad:
            enabled: true # 开启主动加载
        enabled: true # 开启启动阶段加载配置
        namespaces: dev_dept.common_config, dev_dept.common_service_config, application # 指定需要加载的命名空间的配置

server:
    port: 50101 # 项目端口号

