spring:
    application:
        name: jasonlocalhost-blog-web

app:
    id: jlh-web

apollo:
    cluster: blog
    property:
        order:
            enable: true
    bootstrap:
        eagerLoad:
            enabled: true # 开启主动加载
        enabled: true # 开启启动阶段加载配置
        namespaces: dev_dept.application, dev_dept.datasource # 指定需要加载的命名空间的配置

server:
    port: 50003 # 项目端口号


